version: '3.8'
services:
  web:
    build: .
    image: samboi/my-web-app:latest
    ports:
      - "8082:8081"  # Change the host port to 8082, keep the container port as 8081
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
